MVCShoppingMall/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WecareMVC.Models;
using Microsoft.WindowsAzure.Storage.Blob;
using Microsoft.WindowsAzure.Storage;
using System.IO;
using System.Collections.Specialized;
using System.Configuration;

namespace WecareMVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StoreManagerController : Controller
    {
        private MusicStoreEntities db = new MusicStoreEntities();

        // GET: StoreManager/Upload/5
        public async Task<ActionResult> Upload(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = await db.Albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            return View(album);
        }

        // POST: StoreManager/Upload/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Upload([Bind(Include = "AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Album album, int id, HttpPostedFileBase file)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    album.AlbumId = id;
                   
                    if (file.ContentLength > 0)
                    {
                        //只是存資料夾
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/App_Data/Images"),   fileName);
                        file.SaveAs(path);

                        //建立容器
                        //this.CreateContainerExists();

                        //HttpPostedFileBase轉成byte
                        //MemoryStream target = new MemoryStream();
                        //file.InputStream.CopyTo(target);
                        //byte[] data = target.ToArray();
                        //SaveImage(Guid.NewGuid().ToString(), file.FileName, file.ContentType, data);
                        //SaveImage(file);

                        //album.AlbumArtUrl = "https://wecaremvc.blob.core.windows.net/photos/" + file.FileName;
                        album.AlbumArtUrl = path;

                        db.Entry(album).State = EntityState.Modified;
                        await db.SaveChangesAsync();
                    }
                }
                //ViewBag.Message = "Upload successful";
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Message = "Upload failed";
                //return RedirectToAction("Uploads");
                ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
                ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
                return View(album);
            }
        }

        private void SaveImage(HttpPostedFileBase data)
        {
            CloudBlockBlob blob = this.GetContainer().GetBlockBlobReference(data.FileName);
            blob.Properties.ContentType = data.ContentType;
            using (var fileStream = data.InputStream)
            {
                blob.UploadFromStream(fileStream);
            } 
        }

        //存取Image
        private void SaveImage(string id, string fileName, string contentType, byte[] data)
        {
            //利用GetBlobReference來取得Blob，第一個參數會帶進檔案名稱，
            //而此檔案名稱會化成Uri的一部分。https://wecaremvc.blob.core.windows.net/photos/fileName
            CloudBlockBlob blob = this.GetContainer().GetBlockBlobReference(fileName);            
            //檔案型態
            blob.Properties.ContentType = contentType;
            blob.UploadFromByteArray(data,0,data.Length);  
        }

        private CloudBlobContainer GetContainer()
        {
            //取得Storage Account。
            CloudStorageAccount account = CloudStorageAccount.Parse( 
                                 ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);
            //取得Storage的Client
            CloudBlobClient client = account.CreateCloudBlobClient();
            //取得Container關聯。
            return client.GetContainerReference("photos");
        }

        private void CreateContainerExists()
        {
            CloudBlobContainer container = this.GetContainer();
            //假如沒有這個Container，就建立一個。
            container.CreateIfNotExists();

            container.SetPermissions(
             new BlobContainerPermissions
             {
                    PublicAccess = BlobContainerPublicAccessType.Blob
            });
        }


        // GET: StoreManager
        public async Task<ActionResult> Index()
        {
            var albums = db.Albums.Include(a => a.Artist).Include(a => a.Genre);
            return View(await albums.ToListAsync());
        }

        // GET: StoreManager/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = await db.Albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: StoreManager/Create
        public ActionResult Create()
        {
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name");
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name");
            return View();
        }

        // POST: StoreManager/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Album album, HttpPostedFileBase file)
        {
            if (ModelState.IsValid&& file!=null)
            {
                //圖片存資料夾
                
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images/Upload"), fileName);
                    file.SaveAs(path);
                    album.AlbumArtUrl = "/Content/Images/Upload/" + fileName;


                    db.Albums.Add(album);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Details", new { id = album.AlbumId });   
            }

            


            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            ViewBag.uploadInfo = "請選擇圖片！";
            return View(album);
        }

        // GET: StoreManager/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = await db.Albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            return View(album);
        }

        // POST: StoreManager/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Album album, int id, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                album.AlbumId = id;

                //if (file.ContentLength!=0 && file!= null)
                //{
                //    SaveImage(file);
                //    album.AlbumArtUrl = "https://wecaremvc.blob.core.windows.net/photos/" + file.FileName;
                //}
                if (file != null)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images/Upload"), fileName);
                    file.SaveAs(path);
                    album.AlbumArtUrl = "/Content/Images/Upload/" + fileName;
                }
                db.Entry(album).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new {id = album.AlbumId });
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            return View(album);
        }

        // GET: StoreManager/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = await db.Albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: StoreManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {

MVCShoppingMall/Views/StoreManager/Create.cshtml
@model WecareMVC.Models.Album

@{
    ViewBag.Title = "商品上架";
}
<style>
    .btn-file {
        position: relative;
        overflow: hidden;
    }

        .btn-file input[type=file] {
            position: absolute;
            top: 0;
            right: 0;
            min-width: 100%;
            min-height: 100%;
            font-size: 100px;
            text-align: right;
            filter: alpha(opacity=0);
            opacity: 0;
            outline: none;
            background: white;
            cursor: inherit;
            display: block;
        }
</style>
<h2>商品上架</h2>


@using (Html.BeginForm("Create", "StoreManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, "商品分類", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "製造商", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.AlbumArtUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlbumArtUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlbumArtUrl, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumArtUrl, "圖片", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<span id="pUrl" class="text-success h4">@Model.AlbumArtUrl</span>*@
                <span class="btn btn-default btn-file tex">
                    瀏覽...
                    @Html.TextBox("file", "", new { type = "file", id = "FileUpload1" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <img id="img1" src="" class="img-responsive" alt="">
                <h4 class="text-danger">@ViewBag.uploadInfo</h4>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="上架" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回商品管理", "Index")
</div>

MVCShoppingMall/Views/StoreManager/Delete.cshtml
@model WecareMVC.Models.Album
@{
    ViewBag.Title = "商品刪除";
}
<h2>商品刪除確認</h2>
<p>
   確定刪除這項商品嗎？
    <strong>@Model.Title</strong>?
</p>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="刪除" />
    </p>
    <p>
        @Html.ActionLink("回商品管理", "Index")
    </p>
}

MVCShoppingMall/Views/StoreManager/Details.cshtml
@model WecareMVC.Models.Album

@{
    ViewBag.Title = "商品詳細資料";
}

<h3>商品詳細資料 - @Model.Title</h3>

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlbumArtUrl)
        </dt>

        <dd>           
            @Html.DisplayFor(model => model.AlbumArtUrl)
           
        </dd>

        
        <dd><img src="@Model.AlbumArtUrl" class="img-responsive" alt="" /></dd>
    </dl>
</div>
<p>
    @Html.ActionLink("編輯", "Edit", new { id = Model.AlbumId }) |
    @Html.ActionLink("回商品管理", "Index")
</p>

MVCShoppingMall/Views/StoreManager/Edit.cshtml
@model WecareMVC.Models.Album

@{
    ViewBag.Title = "商品編輯";
}

<style>
    .btn-file {
        position: relative;
        overflow: hidden;
    }

        .btn-file input[type=file] {
            position: absolute;
            top: 0;
            right: 0;
            min-width: 100%;
            min-height: 100%;
            font-size: 100px;
            text-align: right;
            filter: alpha(opacity=0);
            opacity: 0;
            outline: none;
            background: white;
            cursor: inherit;
            display: block;
        }
</style>
<h2>商品編輯</h2>

@using (Html.BeginForm("Edit", "StoreManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>商品</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AlbumId)


        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, "商品分類", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "製造商", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumArtUrl, "原圖片URL", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span id="pUrl" class="text-success h4">@Model.AlbumArtUrl</span>
                <span class="btn btn-default btn-file tex">
                    瀏覽...
                    @Html.TextBox("file", "", new { type = "file", id = "FileUpload1" })
                </span>


            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <img id="img1" src="@Model.AlbumArtUrl" class="img-responsive" alt="">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到商品管理", "Index")
</div>

MVCShoppingMall/Views/StoreManager/Index.cshtml
@model IEnumerable<WecareMVC.Models.Album>
@helper Truncate(string input , int length)
{
    if (input.Length<=length)
    {
        @input
    }
    else
    {
       @input.Substring(0, length)<text>...</text>
    }
        
    }


@{
    ViewBag.Title = "Index";
}

<h2>商品管理</h2>

<p>
    @Html.ActionLink("商品上架", "Create")
</p>
<table class="table">
    <tr>
        <th>
            商品分類
        </th>
        <th>
            製造商
        </th>
        <th>
           商品名稱
        </th>
        <th>
            單價
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.AlbumArtUrl)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Genre.Name)
        </td>
        <td>
            @Truncate(item.Artist.Name,25)
        </td>
        <td>
            @Truncate(item.Title,25)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.AlbumArtUrl)
        </td>*@
        <td>
            @Html.ActionLink("編輯", "Edit", new { id=item.AlbumId }) |
            @Html.ActionLink("查看", "Details", new { id=item.AlbumId }) |
            @Html.ActionLink("刪除", "Delete", new { id=item.AlbumId })
        </td>
    </tr>
}

</table>