MVCShoppingMall/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WecareMVC.Models
{
    public partial class ShoppingCart
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();
        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";
        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);  //透過context  取得 context.Session[CartSessionKey]  給cartId
            return cart;
        }

        // Helper method to simplify shopping cart calls
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }

        public void AddToCart(Album album)
        {
            // Get the matching cart and album instances
            var cartItem = storeDB.Carts.SingleOrDefault(
                c => c.CartId == ShoppingCartId
                && c.AlbumId == album.AlbumId);

            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new Cart
                {
                    AlbumId = album.AlbumId,
                    CartId = ShoppingCartId,
                    Count = 1,
                    DateCreated = DateTime.Now
                };
                storeDB.Carts.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, 
                // then add one to the quantity
                cartItem.Count++;
            }
            // Save changes
            storeDB.SaveChanges();
        }


        public int RemoveFromCart(int id)
        {
            // Get the cart
            var cartItem = storeDB.Carts.Single(
                cart => cart.CartId == ShoppingCartId
                && cart.RecordId == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                //if (cartItem.Count > 1)  一次減一個商品
                //{
                //    cartItem.Count--;
                //    itemCount = cartItem.Count;
                //}
                //else
                //{
                     storeDB.Carts.Remove(cartItem);
                //}
                // Save changes
                storeDB.SaveChanges();
            }
            return itemCount;
        }


        public void EmptyCart()  
        {
            var cartItems = storeDB.Carts.Where(            //淨空購物車
                cart => cart.CartId == ShoppingCartId);

            foreach (var cartItem in cartItems)
            {
                storeDB.Carts.Remove(cartItem);
            }
            // Save changes
            storeDB.SaveChanges();
        }

        public List<Cart> GetCartItems()   //取得現在在購物車內的商品
        {
            return storeDB.Carts.Where(
                cart => cart.CartId == ShoppingCartId).ToList();
        }


        public int GetCount()   //取得商品數量，顯示在首頁
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in storeDB.Carts
                          where cartItems.CartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            // Return 0 if all entries are null
            return count ?? 0;
        }


        public decimal GetTotal() //取得總金額
        {
            // Multiply album price by count of that album to get 
            // the current price for each of those albums in the cart
            // sum all album price totals to get the cart total
            decimal? total = (from cartItems in storeDB.Carts
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count *
                              cartItems.Album.Price).Sum();

            return total ?? decimal.Zero;  //若total是空值，則回傳0.00
        }

        public int CreateOrder(Order order, decimal disCount)   //把每一筆購買商品記錄到order中
        {
            decimal orderTotal = 0;

            var cartItems = GetCartItems();  //先取得所有商品
            // Iterate over the items in the cart, 
            // adding the order details for each
            foreach (var item in cartItems)  //每筆存成orderDetail
            {
                var orderDetail = new OrderDetail   
                {
                    AlbumId = item.AlbumId,
                    OrderId = order.OrderId,
                    UnitPrice = item.Album.Price,
                    Quantity = item.Count
                };

                // Set the order total of the shopping cart
                orderTotal += (item.Count * item.Album.Price)*disCount;  //累計取得訂單總價

                storeDB.OrderDetails.Add(orderDetail);

            }
            // Set the order's total to the orderTotal count
            storeDB.Orders.Single(o => o.OrderId == order.OrderId).Total = orderTotal;
            

            // Save the order
            storeDB.SaveChanges();
            // Empty the shopping cart
            EmptyCart();
            // Return the OrderId as the confirmation number
            return order.OrderId;
        }

        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)  
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] =
                        context.User.Identity.Name;      //使用者已經登入，CartID直接設成userEmail
                }
                else
                {
                    // Generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();   //給購物車隨機ID  因為使用者還未登入
                    // Send tempCartId back to client as a cookie
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }

        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string UserEmail)      //登入之後將上面隨機給的ID換成UserEmail
        {
            var shoppingCart = storeDB.Carts.Where(
                c => c.CartId == ShoppingCartId);

            foreach (Cart item in shoppingCart)
            {
                item.CartId = UserEmail;  //把cartid以email標註為某user的
            }
            storeDB.SaveChanges();
        }

        //用來更新數量
        public int UpdateCartCount(int id, int cartCount)
        {
            // Get the cart 
            var cartItem = storeDB.Carts.Single(
                cart => cart.CartId == ShoppingCartId
                && cart.RecordId == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartCount > 0)
                {
                    cartItem.Count = cartCount;
                    itemCount = cartItem.Count;
                }
                else
                {
                    storeDB.Carts.Remove(cartItem);
                }
                // Save changes 
                storeDB.SaveChanges();
            }
            return itemCount;
        }
    }
}

MVCShoppingMall/ViewModels/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WecareMVC.Models;

namespace WecareMVC.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }

    public class ShoppingCartRemoveViewModel
    {
        public string Message { get; set; }
        public decimal CartTotal { get; set; }
        public int CartCount { get; set; }
        public int ItemCount { get; set; }
        public int DeleteId { get; set; }
    }


}

MVCShoppingMall/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WecareMVC.Models;
using WecareMVC.ViewModels;

namespace WecareMVC.Controllers
{
   
        // GET: ShoppingCart
        public class ShoppingCartController : Controller
        {
            MusicStoreEntities storeDB = new MusicStoreEntities();
            //
            // GET: /ShoppingCart/
            public ActionResult Index()
            {
                var cart = ShoppingCart.GetCart(this.HttpContext);

                // Set up our ViewModel
                var viewModel = new ShoppingCartViewModel
                {
                    CartItems = cart.GetCartItems(),
                    CartTotal = cart.GetTotal()
                };
                // Return the view
                return View(viewModel);
            }
            //
            // GET: /Store/AddToCart/5
            public ActionResult AddToCart(int id)
            {
                // Retrieve the album from the database
                var addedAlbum = storeDB.Albums
                    .Single(album => album.AlbumId == id);

                // Add it to the shopping cart
                var cart = ShoppingCart.GetCart(this.HttpContext);

                cart.AddToCart(addedAlbum);

                // Go back to the main store page for more shopping
                return RedirectToAction("Index");
            }
            //
            // AJAX: /ShoppingCart/RemoveFromCart/5
            [HttpPost]
            public ActionResult RemoveFromCart(int id)
            {
                // Remove the item from the cart
                var cart = ShoppingCart.GetCart(this.HttpContext);  
                //傳送HttpContext透過context.Session[CartSessionKey]取得某cartId的cart　

                // Get the name of the album to display confirmation
                string albumName = storeDB.Carts
                    .Single(item => item.RecordId == id).Album.Title;

                // Remove from cart
                int itemCount = cart.RemoveFromCart(id);

                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(albumName) +
                        "已從購物車中移除",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                return Json(results);
            }
            //
            // GET: /ShoppingCart/CartSummary
            [ChildActionOnly]
            public ActionResult CartSummary()
            {
                var cart = ShoppingCart.GetCart(this.HttpContext);

                ViewData["CartCount"] = cart.GetCount();
                return PartialView("_CartSummary");
            }

            [HttpPost]
            public ActionResult UpdateCartCount(int id, int cartCount)
            {
                ShoppingCartRemoveViewModel results = null;
                try
                {
                    // Get the cart 
                    var cart = ShoppingCart.GetCart(this.HttpContext);

                    // Get the name of the album to display confirmation 
                    string albumName = storeDB.Carts
                        .Single(item => item.RecordId == id).Album.Title;

                    // Update the cart count 
                    int itemCount = cart.UpdateCartCount(id, cartCount);

                    //Prepare messages
                    string msg =  Server.HtmlEncode(albumName) +
                            " 的數量已更新！ ";
                    if (itemCount == 0) msg = Server.HtmlEncode(albumName) +
                            " 已移除！ ";
                    //
                    // Display the confirmation message 
                    results = new ShoppingCartRemoveViewModel
                    {
                        Message = msg,
                        CartTotal = cart.GetTotal(),
                        CartCount = cart.GetCount(),
                        ItemCount = itemCount,
                        DeleteId = id
                    };
                }
                catch
                {
                    results = new ShoppingCartRemoveViewModel
                    {
                        Message = "錯誤的輸入數量！",
                        CartTotal = -1,
                        CartCount = -1,
                        ItemCount = -1,
                        DeleteId = id
                    };
                }
                return Json(results);
            }
        }
    }

MVCShoppingMall/Views/ShoppingCart/Index.cshtml
@model WecareMVC.ViewModels.ShoppingCartViewModel


@{
    ViewBag.Title = "Shopping Cart";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script type="text/javascript">


        $(function () {

            $(".RefreshQuantity").click(function () {
                // Get the id from the link
                var recordToUpdate = $(this).attr("data-id");

                //Set quantity number to 0 if input value is empty
                var countToUpdate = 0;
                if ($("#" + $(this).attr("txt-id")).val().trim() !== '') {
                    countToUpdate = $("#" + $(this).attr("txt-id")).val();
                }

                if (recordToUpdate != '') {
                    // Perform the ajax post
                    $.post("/ShoppingCart/UpdateCartCount", { "id": recordToUpdate, "cartCount": countToUpdate },
                        function (data) {
                            // Successful requests get here
                            // Update the page elements
                            if (data.ItemCount == 0) {
                                $('#row-' + data. DeleteId).fadeOut('slow');
                            }
                            $('#update-message').text(htmlDecode(data.Message));
                            $('#cart-total').text('$ '+data.CartTotal);
                            $('#cart-status').text('Cart (' + data.CartCount + ')');
                        });
                }
            })

                // Document.ready -> link up remove event handler
                $(".RemoveLink").click(function () {
                    // Get the id from the link
                    var recordToDelete = $(this).attr("data-id");
                    if (recordToDelete != '') {
                        // Perform the ajax post
                        // Action為：  public ActionResult RemoveFromCart(int id){return Json(result); }
                        // 其中result為ShoppingCartRemoveViewModel
                        $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                            function (data) {
                                // Successful requests get here
                                // Update the page elements
                                //if (data.ItemCount == 0) {
                                $('#row-' + data.DeleteId).fadeOut('slow');      //若數量為0則淡出
                                //} else {
                                //    $('#item-count-' + data.DeleteId).text(data.ItemCount);
                                //}                                
                                $('#update-message').text(data.Message);   //從shoppingcartcontroller回傳錯誤或成功訊息                            
                                //Only process the callback data when no server error occurs
                                if (data.ItemCount != -1) {
                                    $('#cart-total').text('$ ' + data.CartTotal);
                                    $('#cart-status').text('Cart (' + data.CartCount + ')');
                                }
                            });
                    }
                });

                function clearUpdateMessage() {
                    // Reset update-message area
                    $('#update-message').text('');
                }
                function htmlDecode(value) {
                    if (value) {
                        return $('<div />').html(value).text();
                    }
                    else {
                        return '';
                    }
                }
                if (typeof String.prototype.trim !== 'function') {
                    String.prototype.trim = function () {
                        return this.replace(/^\s+|\s+$/g, '');
                    }
                }

            });

        
</script>
@using (Html.BeginForm())
{
  
      //驗證欄位
<div>
     @for (int i = 0; i < Model.CartItems.Count; i++)
     { 
        <p>
             @Html.ValidationMessageFor(model => model.CartItems[i].Count)
        </p> 
     }
</div>
        
<div id="update-message">
</div>

    <div class="col-lg-12">
        <div class="page-header">
            <h1 id="tables">您的購物車</h1>
        </div>
        <div class="bs-component">
            <table class="table table-striped table-hover ">
                <thead>
                    <tr>                        
                        <th>商品名稱</th>
                        <th>單價</th>
                        <th>數量</th>
                    </tr>
                </thead>
                <tbody>
                    @{int ix = 0;}
                    @foreach (var item in Model.CartItems)
    {
                        <tr id="row-@item.RecordId">
                            <td>
                                @Html.ActionLink(item.Album.Title,
"Details", "Store", new { id = item.AlbumId }, null)
                            </td>
                            <td>
                                @item.Album.Price
                            </td>
                       
                            <td>
                                @Html.TextBoxFor(model => model.CartItems[ix].Count,
           new
           {
               
               style = "width:30px; text-align:right;",
               onkeyup = "clearUpdateMessage();",
               onchange = "clearUpdateMessage();",
               @class ="amountBox"
           })
                            </td>
                            <td>
                                <a href="#" class="RefreshQuantity" data-id="@item.RecordId"
                                   txt-id="CartItems_@(ix)__Count">修改數量</a>&nbsp;|&nbsp;
                                <a href="#" class="RemoveLink"
                                   data-id="@item.RecordId">
                                   移除
                                </a>
                            </td>
                        </tr>
        ix++;
    }
                    <tr>
                        <td>
                            總價
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                           $ @Model.CartTotal
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="modal-footer">
                <a href="/Checkout/AddressAndPayment" class="btn btn-primary">確認訂單</a>
                <a href="/Store" class="btn btn-default">繼續購物</a>              
            </div>
            <div id="source-button" class="btn btn-primary btn-xs" style="display: none;">&lt; &gt;</div>
        </div>
        </div>
        }

MVCShoppingMall/Views/ShoppingCart/_CartSummary.cshtml
   @*style="margin-right:7px !important"*@
    <li>
        @*@Html.ActionLink("購物車(" + ViewData["CartCount"] + ")", "Index", "ShoppingCart", new { id = "cart-status" })*@
        @*<a href="/ShoppingCart/Index" id="cart-status" style=" padding-top: 10px !important "><span class="glyphicon glyphicon-shopping-cart" style="font-size:25px;"></span>&nbsp;(@ViewData["CartCount"])</a>*@
        <a href="/ShoppingCart/Index" id="cart-status" style=" padding-top: 10px !important "><span class="glyphicon glyphicon-shopping-cart" style="font-size:25px;"></span>&nbsp;(@ViewData["CartCount"])</a>
    </li>   